### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by khelfen** [htw-nus/A8_gaussian-elimination#1]
### Check-Liste aller To-Do's, die mit der Programmierung zu tun haben

- [x] **Erstellung des "Read-In"-Programms**
    - [x] Einlesen einer Matrix
        - [x] Format checken (Soll: 3x3)
        - [x] Type checken (soll nur Zahlen ~~bzw. Variablen~~ enthalten)
        - [x] Lineare Unabhängigkeit der Gleichungen untereinander überprüfen
            + Fall "nicht Unabhängig": [unendlich viele Lösungen](https://www.mathebibel.de/lineare-abhaengigkeit-drei-vektoren)
    - [x] Einlesen des Lösungsvektors
        - [x] Format checken (Soll: 3x1 oder 1x3)
        - [x] Type checken (soll nur Zahlen ~~bzw. Variablen~~ enthalten)
        - [x] umwandeln in 3x1 Column-Vektor
    - [ ] ~~Sind Variablen enthalten?~~
        - [ ] ~~Wenn "Ja", dann keine Grafik erstellen~~
        - [ ] ~~Wenn "Nein", dann Grafik erstellen~~
        - [ ] ~~Information abspeichern und weitergeben~~
        - [ ] ~~Wie viele Variablen sind zulässig? *Ich hätte gesagt max. 1x in der Matrix und 1x im Lösungsvektor*~~
    - [x] Kommentierung jeder Zeile erstellen
    - [x] Hilfetext erstellen

- [ ] **Erstellung des Gauß-Programms**
   - [ ] ~~Linearität der einzelnen Gleichungen überprüfen~~
    - [ ] Lösen des Gleichungssystems, mit
        - [ ] Zeilenskalierung und
        - [ ] Spaltenpivotisierung
    - [ ] Kommentierung jeder Zeile erstellen
    - [ ] Optionale Exportfunktion der Lösung

- [ ] **Erstellung des Programms zur grafischen Darstellung der Lösung**
    - [ ] Optionale Exportfunktion des Plots
    * [Bsp.](https://www.mathwarehouse.com/algebra/planes/systems/three-variable-equations.php)
